// Plain-language labels for audit events ("Wrote secret" instead of
// "KvService/Write"), and the category each belongs to.

import type { AuditEvent } from '../gen/timika/v1/audit_pb'

export type Category = 'signin' | 'secrets' | 'servers' | 'sessions' | 'files' | 'automation' | 'users' | 'system'

const LABELS: Record<string, [string, Category]> = {
  'KvService/Write': ['Wrote secret', 'secrets'],
  'KvService/Read': ['Read secret', 'secrets'],
  'KvService/List': ['Listed folder', 'secrets'],
  'KvService/GetMetadata': ['Viewed secret history', 'secrets'],
  'KvService/Delete': ['Deleted secret version', 'secrets'],
  'KvService/Destroy': ['Destroyed secret', 'secrets'],
  'AuthService/Login': ['Signed in', 'signin'],
  'AuthService/RevokeSelf': ['Signed out', 'signin'],
  'AuthService/RenewSelf': ['Session kept alive', 'signin'],
  'AuthService/LookupSelf': ['Session check', 'signin'],
  'AuthService/ChangePassword': ['Changed own password', 'signin'],
  'AuthService/UpsertUser': ['Created or updated user', 'users'],
  'AuthService/DeleteUser': ['Deleted user', 'users'],
  'AuthService/UnlockUser': ['Unlocked user', 'users'],
  'AuthService/GetUser': ['Viewed user', 'users'],
  'AuthService/ListUsers': ['Listed users', 'users'],
  'BastionService/CreateAsset': ['Added server', 'servers'],
  'BastionService/UpdateAsset': ['Edited server', 'servers'],
  'BastionService/DeleteAsset': ['Deleted server', 'servers'],
  'BastionService/TestAsset': ['Tested server login', 'servers'],
  'BastionService/ResetHostKey': ['Reset host key', 'servers'],
  'BastionService/CreateGrant': ['Granted server access', 'servers'],
  'BastionService/DeleteGrant': ['Revoked server access', 'servers'],
  'BastionService/ListAssets': ['Listed servers', 'servers'],
  'BastionService/ListGrants': ['Viewed server access', 'servers'],
  'BastionService/ListAllGrants': ['Viewed server access', 'servers'],
  'BastionService/ListSessions': ['Viewed sessions', 'sessions'],
  'BastionService/KillSession': ['Ended a session', 'sessions'],
  'BastionService/GetRecording': ['Replayed a recording', 'sessions'],
  'GET /v1/bastion/connect': ['Opened terminal', 'sessions'],
  'BastionService/ListFiles': ['Browsed files', 'files'],
  'BastionService/MakeDir': ['Created a folder', 'files'],
  'BastionService/RenameFile': ['Renamed a file', 'files'],
  'BastionService/DeleteFiles': ['Deleted files', 'files'],
  'BastionService/DownloadLink': ['Prepared a download', 'files'],
  'GET /v1/bastion/files/download': ['Downloaded a file', 'files'],
  'PUT /v1/bastion/files/upload': ['Uploaded a file', 'files'],
  'BastionService/Compress': ['Compressed files', 'files'],
  'BastionService/Extract': ['Extracted an archive', 'files'],
  'BastionService/ArchiveLink': ['Prepared an archive download', 'files'],
  'BastionService/ListCommands': ['Viewed commands', 'sessions'],
  'session live': ['Terminal session started', 'sessions'],
  'session closed': ['Terminal session ended', 'sessions'],
  'session killed': ['Session ended by an admin', 'sessions'],
  'session failed': ['Terminal connection failed', 'sessions'],
  'AutomationService/CreateRepo': ['Connected a repository', 'automation'],
  'AutomationService/UpdateRepo': ['Changed repository settings', 'automation'],
  'AutomationService/DeleteRepo': ['Removed a repository', 'automation'],
  'AutomationService/SyncRepo': ['Pulled a repository', 'automation'],
  'AutomationService/NewDeployKey': ['Generated a deploy key', 'automation'],
  'AutomationService/CheckRunner': ['Checked a runner server', 'automation'],
  'AutomationService/StartRun': ['Started a run', 'automation'],
  'AutomationService/CancelRun': ['Cancelled a run', 'automation'],
  'AutomationService/ApproveRun': ['Approved a run', 'automation'],
  'AutomationService/RejectRun': ['Rejected a run', 'automation'],
  'AutomationService/SaveSchedule': ['Saved a schedule', 'automation'],
  'AutomationService/DeleteSchedule': ['Deleted a schedule', 'automation'],
  'AutomationService/RunScheduleNow': ['Ran a schedule now', 'automation'],
  'AutomationService/ListSchedules': ['Viewed schedules', 'automation'],
  'AutomationService/SetRepoPolicy': ['Changed approval policy', 'automation'],
  'AutomationService/SaveNotifiers': ['Changed notifications', 'automation'],
  'AutomationService/TestNotifier': ['Sent a test notification', 'automation'],
  'AutomationService/RotateTriggerToken': ['Rotated the CI token', 'automation'],
  'AutomationService/ListRepoFiles': ['Browsed repository files', 'automation'],
  'AutomationService/ReadRepoFile': ['Read a repository file', 'automation'],
  'AutomationService/ListRepos': ['Viewed repositories', 'automation'],
  'AutomationService/GetRepo': ['Viewed a repository', 'automation'],
  'AutomationService/ListRuns': ['Viewed runs', 'automation'],
  'AutomationService/GetRun': ['Viewed a run', 'automation'],
  'AutomationService/WatchRun': ['Watched run output', 'automation'],
  'MonitorService/SetMonitoring': ['Changed which servers are monitored', 'servers'],
  'MonitorService/SetSystemAlerts': ['Changed a server\'s alert rules', 'servers'],
  'MonitorService/SaveSettings': ['Changed monitoring alerts & notifications', 'servers'],
  'MonitorService/TestNotifier': ['Sent a test notification', 'servers'],
  'SourceService/SaveSource': ['Added or changed a map source', 'servers'],
  'SourceService/DeleteSource': ['Removed a map source', 'servers'],
  'SourceService/RefreshSource': ['Read a map source', 'servers'],
  'NginxService/GetInstance': ['Opened an nginx', 'servers'],
  'NginxService/ReadFile': ['Read an nginx config file', 'servers'],
  'NginxService/SaveFile': ['Changed an nginx config file', 'servers'],
  'NginxService/SetEnabled': ['Switched an nginx site on / off', 'servers'],
  'NginxService/DeleteFile': ['Deleted an nginx config file', 'servers'],
  'NginxService/Reload': ['Tested and reloaded nginx', 'servers'],
  'NginxService/GetVersion': ['Read an earlier version of an nginx config file', 'servers'],
  'NginxService/ReadLog': ['Read an nginx log', 'servers'],
  'NetService/Run': ['Ran a network check', 'servers'],
  'ContainerService/InspectContainer': ['Viewed container details', 'servers'],
  'ContainerService/ListFiles': ['Browsed files in a container', 'files'],
  'ContainerService/MakeDir': ['Created a folder in a container', 'files'],
  'ContainerService/DeleteFiles': ['Deleted files in a container', 'files'],
  'ContainerService/DownloadLink': ['Prepared a download from a container', 'files'],
  'GET /v1/containers/download': ['Downloaded from a container', 'files'],
  'PUT /v1/containers/upload': ['Uploaded into a container', 'files'],
  'ContainerService/ListImages': ['Viewed images', 'servers'],
  'ContainerService/RemoveImage': ['Removed an image', 'servers'],
  'ContainerService/PruneImages': ['Pruned unused images', 'servers'],
  'ContainerService/ListVolumes': ['Viewed volumes', 'servers'],
  'ContainerService/RemoveVolume': ['Removed a volume', 'servers'],
  'ContainerService/PruneVolumes': ['Pruned unused volumes', 'servers'],
  'MonitorService/ContainerLogs': ['Read container logs', 'servers'],
  'MonitorService/ContainerAction': ['Started / stopped a container', 'servers'],
  'MonitorService/SetMapMethod': ['Changed how the map is detected', 'servers'],
  'MonitorService/GetMap': ['Viewed the network map', 'servers'],
  'MonitorService/ListContainers': ['Viewed containers', 'servers'],
  'MonitorService/ListSystems': ['Viewed monitoring', 'servers'],
  'MonitorService/GetSystem': ['Viewed a server\'s metrics', 'servers'],
  'MonitorService/GetSettings': ['Viewed monitoring settings', 'servers'],
  'SysService/Init': ['Initialized vault', 'system'],
  'SysService/Unseal': ['Submitted unseal key', 'system'],
  'SysService/Seal': ['Sealed vault', 'system'],
  'SysService/Rotate': ['Rotated encryption key', 'system'],
  'SysService/GetKeyStatus': ['Viewed key status', 'system'],
  'SysService/Storage': ['Viewed storage status', 'system'],
  'SysService/Audit': ['Viewed audit settings', 'system'],
  'SysService/AuditHash': ['Looked up a value in the audit log', 'system'],
  'AuditService/ListEvents': ['Viewed audit trail', 'system'],
  'AuditService/Verify': ['Verified audit log integrity', 'system'],
  'ClusterService/Configuration': ['Viewed cluster', 'system'],
  'ClusterService/RemovePeer': ['Removed cluster node', 'system'],
  'ClusterService/Snapshot': ['Downloaded snapshot', 'system'],
  'ClusterService/JoinChallenge': ['Node asked to join', 'system'],
  'ClusterService/JoinAnswer': ['Node joined', 'system'],
}

/** gRPC status codes → short names. */
export const CODE_NAMES: Record<number, string> = {
  1: 'cancelled', 2: 'unknown', 3: 'invalid', 4: 'timeout', 5: 'not found', 6: 'exists', 7: 'denied',
  8: 'rate limited', 9: 'precondition', 10: 'conflict', 12: 'unimplemented', 13: 'internal', 14: 'unavailable', 16: 'unauthenticated',
}

export function describe(e: Pick<AuditEvent, 'action' | 'ok' | 'kind' | 'code'>): { label: string; category: Category } {
  if (e.action.startsWith('POST /v1/automation/hooks/')) return { label: e.ok ? 'Push webhook received' : 'Push webhook refused', category: 'automation' }
  if (e.action.startsWith('POST /v1/automation/trigger/')) return { label: e.ok ? 'Run started from CI' : 'CI trigger refused', category: 'automation' }
  const hit = LABELS[e.action]
  if (!hit) return { label: e.action, category: 'system' }
  let [label, category] = hit
  if (!e.ok && e.action === 'AuthService/Login') label = 'Sign-in failed'
  if (!e.ok && e.action === 'GET /v1/bastion/connect') label = 'Terminal refused'
  return { label, category }
}

export const outcome = (e: Pick<AuditEvent, 'ok' | 'code' | 'kind'>) =>
  e.ok ? 'ok' : e.kind === 'call' && e.code < 100 ? CODE_NAMES[e.code] ?? `code ${e.code}` : e.kind === 'call' ? `HTTP ${e.code}` : 'failed'
